(async function () {
  const SOURCE_URLS = {
    geometry:
      "https://opendata.paris.fr/api/explore/v2.1/catalog/datasets/secteurs-des-bureaux-de-vote-2026/exports/geojson?limit=-1",
    round1Page: "https://www.paris.fr/elections/municipales-2026-premier-tour",
    round2Page: "https://www.paris.fr/elections/municipales-2026-second-tour",
    round1Json:
      "https://cdn.paris.fr/paris/2026/03/18/dc6eb426c9a69721c40d845492d6046c.json",
    round2Json:
      "https://cdn.paris.fr/paris/2026/03/23/1c44370057138acd63333e945033e3a3.json",
  };

  const STATIC_HISTORY = [
    {
      year: "1995",
      label: "1995",
      firstDate: "11 juin 1995",
      secondDate: "18 juin 1995",
      turnout: { first: 49.69, second: 53.05 },
      winner: {
        name: "Jean Tiberi",
        partyLabel: { fr: "Droite parlementaire", en: "Parliamentary right" },
        shortLabel: { fr: "Droite", en: "Right" },
        color: "#2f6fdf",
      },
      shares: [
        { id: "right", label: { fr: "Droite parlementaire", en: "Parliamentary right" }, color: "#2f6fdf", first: 47.73, second: 47.9 },
        { id: "left", label: { fr: "Gauche parlementaire", en: "Parliamentary left" }, color: "#e14b5a", first: 34.58, second: 46.47 },
        { id: "ecology", label: { fr: "Écologie", en: "Ecology" }, color: "#2b9348", first: 7.12, second: 0 },
        { id: "farRight", label: { fr: "Extrême droite", en: "Far right" }, color: "#6a4c93", first: 10.04, second: 5.62 },
      ],
      notes: {
        fr: "Première municipale parisienne de la période demandée. Il n’existe pas d’élection municipale parisienne en 1990 ; la série électorale commence ici en juin 1995.",
        en: "This is the first Paris municipal election in the requested range. There was no Paris municipal election in 1990; the electoral series starts here in June 1995.",
      },
      source: "https://fr.wikipedia.org/wiki/%C3%89lections_municipales_de_1995_%C3%A0_Paris",
    },
    {
      year: "2001",
      label: "2001",
      firstDate: "11 mars 2001",
      secondDate: "18 mars 2001",
      turnout: { first: 62.45, second: 64.13 },
      winner: {
        name: "Bertrand Delanoë",
        partyLabel: { fr: "Gauche plurielle", en: "Plural left" },
        shortLabel: { fr: "Gauche", en: "Left" },
        color: "#e14b5a",
      },
      shares: [
        { id: "left", label: { fr: "Gauche plurielle", en: "Plural left" }, color: "#e14b5a", first: 31.31, second: 49.6 },
        { id: "right", label: { fr: "Droite classique", en: "Mainstream right" }, color: "#2f6fdf", first: 25.74, second: 36.17 },
        { id: "dissRight", label: { fr: "Droite dissidente", en: "Dissident right" }, color: "#6f7fb7", first: 13.92, second: 12.31 },
        { id: "greens", label: { fr: "Écologistes", en: "Greens" }, color: "#2b9348", first: 12.35, second: 0 },
      ],
      notes: {
        fr: "Basculer à 2001 permet de voir la conquête de Paris par Bertrand Delanoë. Les écologistes sont ici séparés de la gauche socialiste, contrairement au raccourci fautif que tu signalais.",
        en: "Switching to 2001 shows Bertrand Delanoe’s takeover of Paris. Greens are kept separate from the socialist left here, instead of being folded into it.",
      },
      source: "https://fr.wikipedia.org/wiki/%C3%89lections_municipales_de_2001_%C3%A0_Paris",
    },
    {
      year: "2008",
      label: "2008",
      firstDate: "9 mars 2008",
      secondDate: "16 mars 2008",
      turnout: { first: 56.93, second: 56.67 },
      winner: {
        name: "Bertrand Delanoë",
        partyLabel: { fr: "Gauche municipale", en: "Municipal left" },
        shortLabel: { fr: "Gauche", en: "Left" },
        color: "#e14b5a",
      },
      shares: [
        { id: "left", label: { fr: "PS-PCF-PRG-MRC", en: "Social-democratic left" }, color: "#e14b5a", first: 41.6, second: 57.71 },
        { id: "right", label: { fr: "UMP et alliés", en: "UMP and allies" }, color: "#2f6fdf", first: 27.92, second: 36.07 },
        { id: "center", label: { fr: "Centre (MoDem)", en: "Centre (MoDem)" }, color: "#f08c00", first: 9.06, second: 2.36 },
        { id: "greens", label: { fr: "Écologistes", en: "Greens" }, color: "#2b9348", first: 6.78, second: 0 },
      ],
      notes: {
        fr: "Le centre pèse encore fortement en 2008, tandis que les écologistes restent autonomes au premier tour avant fusion.",
        en: "The centre still matters a lot in 2008, while Greens remain autonomous in the first round before merging.",
      },
      source: "https://fr.wikipedia.org/wiki/%C3%89lections_municipales_de_2008_%C3%A0_Paris",
    },
    {
      year: "2014",
      label: "2014",
      firstDate: "23 mars 2014",
      secondDate: "30 mars 2014",
      turnout: { first: 54.17, second: 58.03 },
      winner: {
        name: "Anne Hidalgo",
        partyLabel: { fr: "Gauche social-démocrate", en: "Social-democratic left" },
        shortLabel: { fr: "Gauche", en: "Left" },
        color: "#e14b5a",
      },
      shares: [
        { id: "right", label: { fr: "UMP-UDI-MoDem", en: "UMP-UDI-MoDem" }, color: "#2f6fdf", first: 35.91, second: 44.06 },
        { id: "left", label: { fr: "PS-PCF-PRG", en: "Social-democratic left" }, color: "#e14b5a", first: 34.4, second: 53.33 },
        { id: "greens", label: { fr: "Écologistes", en: "Greens" }, color: "#2b9348", first: 8.86, second: 0 },
        { id: "lfiLike", label: { fr: "Gauche radicale", en: "Radical left" }, color: "#d9487a", first: 4.94, second: 1.35 },
      ],
      notes: {
        fr: "Anne Hidalgo gagne Paris en 2014. La gauche radicale, ici portée par Danielle Simonnet, est distinguée des écologistes.",
        en: "Anne Hidalgo wins Paris in 2014. The radical left, led here by Danielle Simonnet, is kept separate from the Greens.",
      },
      source: "https://fr.wikipedia.org/wiki/%C3%89lections_municipales_de_2014_%C3%A0_Paris",
    },
    {
      year: "2020",
      label: "2020",
      firstDate: "15 mars 2020",
      secondDate: "28 juin 2020",
      turnout: { first: 42.3, second: 36.7 },
      winner: {
        name: "Anne Hidalgo",
        partyLabel: { fr: "Gauche municipale", en: "Municipal left" },
        shortLabel: { fr: "Gauche", en: "Left" },
        color: "#e14b5a",
      },
      shares: [
        { id: "left", label: { fr: "PS-PCF-alliés", en: "Social-democratic left" }, color: "#e14b5a", first: 29.33, second: 48.49 },
        { id: "right", label: { fr: "LR et alliés", en: "Republican right" }, color: "#2f6fdf", first: 22.72, second: 34.31 },
        { id: "center", label: { fr: "Centre macroniste", en: "Macronist centre" }, color: "#f08c00", first: 25.14, second: 13.98 },
        { id: "greens", label: { fr: "Écologistes", en: "Greens" }, color: "#2b9348", first: 10.79, second: 0 },
        { id: "lfiLike", label: { fr: "LFI et gauche radicale", en: "LFI and radical left" }, color: "#d9487a", first: 4.57, second: 1.06 },
      ],
      notes: {
        fr: "2020 est la bonne comparaison pour rappeler que LFI n’est pas un parti écologiste. Ici, la liste Simonnet reste distincte de la liste Belliard.",
        en: "2020 is the right comparison point to show that LFI is not a Green party. Simonnet’s list stays distinct from Belliard’s Green list.",
      },
      source: "https://fr.wikipedia.org/wiki/%C3%89lections_municipales_de_2020_%C3%A0_Paris",
    },
  ];

  const DEMOGRAPHY = {
    population: [
      { year: 1990, value: 2152423 },
      { year: 1999, value: 2125246 },
      { year: 2009, value: 2234105 },
      { year: 2014, value: 2220445 },
      { year: 2020, value: 2145906 },
    ],
    tertiary: [
      { year: 2010, value: 55.0 },
      { year: 2015, value: 59.0 },
    ],
    sourcePopulation: "https://www.insee.fr/fr/statistiques/7633058?geo=COM-75056",
    sourceEducation: "https://www.insee.fr/fr/statistiques/3568823?geo=COM-75056",
  };

  const I18N = {
    fr: {
      eyebrow: "Paris municipales",
      heroTitle: "Paris, bureau par bureau et décennie par décennie.",
      heroText:
        "La carte reste centrée sur 2026 au niveau bureau, avec une vue simplifiée arrondissement. À côté, une chronologie remonte jusqu’aux municipales de 1995, et un volet démographie montre comment la capitale et son électorat ont évolué.",
      language: "Langue",
      section: "Section",
      election: "Élection",
      round: "Tour",
      granularity: "Granularité",
      observe: "Observer",
      partyOrList: "Parti ou liste",
      candidateHint: "Le point coloré rappelle la famille politique actuellement sélectionnée.",
      map: "Carte 2026",
      history: "Chronologie",
      demography: "Démographie",
      bureau: "Bureaux",
      arrondissement: "Arrondissements",
      firstRound: "Premier tour",
      secondRound: "Second tour",
      leader: "Tête",
      turnout: "Participation",
      voteShare: "Part des voix",
      currentWinner: "Gagnant courant",
      currentWinnerFootnote:
        "Le bloc gagnant suit le tour affiché. La carte détaillée est volontairement limitée à 2026, la série historique étant restituée à une maille plus simple.",
      no1990:
        "Pas d’élection municipale parisienne en 1990 : la série électorale démarre ici en juin 1995.",
      mapKicker: "Carte mobile-first",
      historyKicker: "Chronologie",
      demographyKicker: "Démographie",
      reset: "Réinitialiser",
      turnoutAtBureau: "Participation au niveau bureau",
      historicalWindow: "Municipales 1995-2026",
      liveFeed: "Flux officiels Ville de Paris",
      mapSummary: "Résumé de la carte",
      selected: "Sélection",
      howToRead: "Comment lire la carte",
      hoverOrTap: "Survolez ou touchez un secteur",
      hoverText:
        "En mode arrondissement, chaque bureau reprend la couleur agrégée de son arrondissement. En mode bureaux, la carte montre la finesse maximale disponible pour 2026.",
      selectedBureau: "Bureau sélectionné",
      selectedArr: "Arrondissement sélectionné",
      leaderLabel: "Bloc en tête",
      expressedVotes: "Suffrages exprimés",
      registered: "Inscrits",
      turnoutLabel: "Participation",
      counted: "Dépouillé",
      stillCounting: "Toujours signalé en dépouillement",
      winnerCard: "Tête à Paris",
      strongestArea: "Zone la plus favorable",
      topTurnout: "Mobilisation la plus forte",
      districtsLed: "Arrondissements dominés",
      sourceTitle: "Sources et méthode",
      mapTitleLive: "Paris 2026, carte vivante",
      liveOnly:
        "La maille bureau est disponible pour 2026. Les années 1995 à 2020 sont restituées dans l’onglet chronologie avec des séries plus synthétiques.",
      historyTitle: "Municipales parisiennes depuis 1995",
      demographyTitle: "Paris change, le vote aussi",
      historyChartTitle: "Rapports de force",
      historyEvolutionTitle: "Lecture politique",
      demoSummaryTitle: "Repères démographiques",
      populationTitle: "Population municipale",
      educationTitle: "Part de diplômés du supérieur",
      populationFootnote:
        "Source : Insee, population en historique depuis 1968 pour la commune de Paris (75056).",
      educationFootnote:
        "Série comparable de diplôme disponible ici à partir de 2010 dans cette version de l’app.",
      sourceFootnote:
        "2026 : Ville de Paris. Historique électoral : synthèses publiques des municipales parisiennes. Démographie : Insee.",
      tooltipTurnout: "Participation",
      tooltipLeader: "Tête",
      tooltipRegistered: "Inscrits",
      leadShare: "Score de tête",
      arrondissementSuffix: "e arrondissement",
      parisCentre: "Paris Centre",
      loading: "Chargement",
      loadingCopy: "Récupération de la géométrie 2026 et des résultats officiels.",
      loadError: "Erreur de chargement",
      historyNotesLabel: "Ce qu’il faut retenir",
      firstRoundShare: "1er tour",
      secondRoundShare: "2d tour",
      winnerByYear: "Vainqueur par cycle",
      population1990: "Population depuis 1990",
      tertiarySince2010: "Supérieur depuis 2010",
      mapDescription: "Vue locale 2026",
      sources: "Sources",
    },
    en: {
      eyebrow: "Paris mayoral elections",
      heroTitle: "Paris, from polling station detail to long-run change.",
      heroText:
        "The map stays focused on 2026 at polling-station level, with a simplified district view. Alongside it, a timeline goes back to the 1995 municipal election, and a demography section tracks how the capital and its electorate have changed.",
      language: "Language",
      section: "Section",
      election: "Election",
      round: "Round",
      granularity: "Granularity",
      observe: "Observe",
      partyOrList: "Party or list",
      candidateHint: "The colored dot reflects the political family currently selected.",
      map: "2026 map",
      history: "Timeline",
      demography: "Demography",
      bureau: "Polling stations",
      arrondissement: "Districts",
      firstRound: "First round",
      secondRound: "Second round",
      leader: "Leader",
      turnout: "Turnout",
      voteShare: "Vote share",
      currentWinner: "Current winner",
      currentWinnerFootnote:
        "The winning bloc follows the round on screen. Detailed mapping is intentionally limited to 2026, while older elections are shown in a simpler historical layer.",
      no1990:
        "There was no Paris municipal election in 1990, so the electoral series shown here starts in June 1995.",
      mapKicker: "Mobile-first map",
      historyKicker: "Timeline",
      demographyKicker: "Demography",
      reset: "Reset",
      turnoutAtBureau: "Turnout at polling-station level",
      historicalWindow: "Municipal elections 1995-2026",
      liveFeed: "Live Ville de Paris feeds",
      mapSummary: "Map snapshot",
      selected: "Selection",
      howToRead: "How to read the map",
      hoverOrTap: "Hover or tap an area",
      hoverText:
        "In district mode, each polling station inherits the aggregate color of its district. In polling-station mode, the map uses the finest available 2026 geometry.",
      selectedBureau: "Selected polling station",
      selectedArr: "Selected district",
      leaderLabel: "Leading bloc",
      expressedVotes: "Expressed votes",
      registered: "Registered voters",
      turnoutLabel: "Turnout",
      counted: "Counted",
      stillCounting: "Still flagged as counting",
      winnerCard: "Citywide leader",
      strongestArea: "Strongest area",
      topTurnout: "Highest turnout",
      districtsLed: "Districts led",
      sourceTitle: "Sources and method",
      mapTitleLive: "Paris 2026, live map",
      liveOnly:
        "Polling-station geometry is available for 2026. The 1995-2020 cycles are shown in the timeline tab with more synthetic series.",
      historyTitle: "Paris municipal elections since 1995",
      demographyTitle: "Paris changes, so does the vote",
      historyChartTitle: "Balance of forces",
      historyEvolutionTitle: "Political reading",
      demoSummaryTitle: "Demographic anchors",
      populationTitle: "Municipal population",
      educationTitle: "Share with tertiary education",
      populationFootnote:
        "Source: Insee, historical population series for the commune of Paris (75056).",
      educationFootnote:
        "Comparable education data starts in 2010 in this version of the app.",
      sourceFootnote:
        "2026: Ville de Paris. Electoral history: public summaries of Paris municipal elections. Demography: Insee.",
      tooltipTurnout: "Turnout",
      tooltipLeader: "Leader",
      tooltipRegistered: "Registered",
      leadShare: "Lead share",
      arrondissementSuffix: "th arrondissement",
      parisCentre: "Paris Centre",
      loading: "Loading",
      loadingCopy: "Fetching 2026 geometry and official results.",
      loadError: "Load error",
      historyNotesLabel: "What stands out",
      firstRoundShare: "Round 1",
      secondRoundShare: "Round 2",
      winnerByYear: "Winner by cycle",
      population1990: "Population since 1990",
      tertiarySince2010: "Tertiary degree since 2010",
      mapDescription: "Local 2026 view",
      sources: "Sources",
    },
  };

  const state = {
    language: "fr",
    section: "map",
    year: "2026",
    round: "round2",
    granularity: "bureau",
    metric: "leader",
    candidate: null,
    hoveredKey: null,
    selectedKey: null,
  };

  const dom = {
    eyebrow: document.getElementById("eyebrow"),
    heroTitle: document.getElementById("hero-title"),
    heroText: document.getElementById("hero-text"),
    winnerBanner: document.getElementById("winner-banner"),
    heroMeta: document.getElementById("hero-meta"),
    languageLabel: document.getElementById("language-label"),
    languageToggle: document.getElementById("language-toggle"),
    sectionLabel: document.getElementById("section-label"),
    sectionToggle: document.getElementById("section-toggle"),
    yearGroup: document.getElementById("year-group"),
    yearLabel: document.getElementById("year-label"),
    yearToggle: document.getElementById("year-toggle"),
    roundGroup: document.getElementById("round-group"),
    roundLabel: document.getElementById("round-label"),
    roundToggle: document.getElementById("round-toggle"),
    granularityGroup: document.getElementById("granularity-group"),
    granularityLabel: document.getElementById("granularity-label"),
    granularityToggle: document.getElementById("granularity-toggle"),
    metricGroup: document.getElementById("metric-group"),
    metricLabel: document.getElementById("metric-label"),
    metricToggle: document.getElementById("metric-toggle"),
    candidateGroup: document.getElementById("candidate-group"),
    candidateLabel: document.getElementById("candidate-label"),
    candidateHint: document.getElementById("candidate-hint"),
    candidateShell: document.getElementById("candidate-shell"),
    candidateDot: document.getElementById("candidate-dot"),
    candidateSelect: document.getElementById("candidate-select"),
    mapView: document.getElementById("map-view"),
    mapKicker: document.getElementById("map-kicker"),
    mapTitle: document.getElementById("map-title"),
    mapSummary: document.getElementById("map-summary"),
    detailCard: document.getElementById("detail-card"),
    legend: document.getElementById("legend"),
    resetView: document.getElementById("reset-view"),
    historyView: document.getElementById("history-view"),
    historyKicker: document.getElementById("history-kicker"),
    historyTitle: document.getElementById("history-title"),
    historySummary: document.getElementById("history-summary"),
    historyChart: document.getElementById("history-chart"),
    historyEvolution: document.getElementById("history-evolution"),
    demographyView: document.getElementById("demography-view"),
    demographyKicker: document.getElementById("demography-kicker"),
    demographyTitle: document.getElementById("demography-title"),
    demoSummary: document.getElementById("demo-summary"),
    demoPopulation: document.getElementById("demo-population"),
    demoEducation: document.getElementById("demo-education"),
    summaryCard: document.getElementById("summary-card"),
    sourceCard: document.getElementById("source-card"),
  };

  ...